[target.'cfg(any())']
rustflags = [
    "-C", "target-cpu=native",
    "-C", "opt-level=3",
    "-C", "lto=fat",
    "-C", "codegen-units=1",
    "-C", "inline-threshold=275",
    "-C", "llvm-args=-unroll-threshold=1000"
]

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
strip = true
overflow-checks = false
debug = false
debug-assertions = false
incremental = false